export const REGISTER_REQUEST = 'REGISTER_REQUEST'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const LOGIN = 'LOGIN'

export const LOGOUT = 'LOGOUT'

export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_REQUEST'

export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS'

export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE'